# Generated by Django 3.2.20 on 2024-01-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_for_id', models.IntegerField()),
                ('book_for_type', models.CharField(max_length=225)),
                ('from_date', models.CharField(max_length=225)),
                ('from_time', models.CharField(max_length=225)),
                ('to_date', models.CharField(max_length=225)),
                ('to_time', models.CharField(max_length=225)),
                ('b_quantity', models.CharField(max_length=225)),
                ('returned_date', models.CharField(max_length=225)),
                ('booking_status', models.CharField(max_length=225)),
                ('booked_datetime', models.CharField(max_length=225)),
                ('balance_amount', models.CharField(max_length=225)),
                ('driver', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('usertype', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='owners',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('second_name', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('image', models.FileField(upload_to='')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='rent',
            fields=[
                ('rent_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_km', models.CharField(max_length=225)),
                ('rate', models.CharField(max_length=225)),
                ('duration', models.CharField(max_length=225)),
                ('extra_km_rate', models.CharField(max_length=225)),
                ('date_time', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=225)),
                ('model', models.CharField(max_length=225)),
                ('colour', models.CharField(max_length=225)),
                ('no_seat', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('per_day_rent', models.CharField(max_length=225)),
                ('car_status', models.CharField(max_length=225)),
                ('vehicle_image', models.FileField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.owners')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('second_name', models.CharField(max_length=225)),
                ('house_name', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('pincode', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('adhar_card', models.CharField(max_length=225)),
                ('driving_license_back', models.FileField(upload_to='')),
                ('driving_license_front', models.FileField(upload_to='')),
                ('picture', models.FileField(upload_to='')),
                ('latitude', models.CharField(max_length=225)),
                ('logitu', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=225)),
                ('amount', models.CharField(max_length=225)),
                ('datetime', models.CharField(max_length=225)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=225)),
                ('quantity', models.CharField(max_length=225)),
                ('rent_per_item', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('image', models.FileField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.owners')),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=225)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('datetime', models.CharField(max_length=225)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='chatz',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=225)),
                ('date_time', models.CharField(max_length=225)),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='car_rental_app.login')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to='car_rental_app.login')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.users'),
        ),
    ]
